### ISSUE TITLE
Plugin fails to load when loaded through different dependency paths

### ISSUE THREAD

**Issue by lptr** [nebula-plugins/gradle-dependency-lock-plugin#40]
When there are two projects in a multi-project build that use different `classpath`s to load the dependency-lock plugin, the plugin fails to load.

Example:

* `project-a` depends on `my-plugin:1.0` which depends on the `gradle-dependency-lock-plugin:2.0.1`.
* `project-b` depends on `my-other-plugin:3.7` which depends on the `gradle-dependency-lock-plugin:2.0.1`.

In this case Gradle loads the dependency-lock plugin twice, and this part in `DependencyLockPlugin` fails:

```groovy
        DependencyLockCommitExtension commitExtension = project.rootProject.extensions.findByType(DependencyLockCommitExtension)
        if (!commitExtension) {
            commitExtension = project.rootProject.extensions.create('commitDependencyLock', DependencyLockCommitExtension)
        }
```

Because `findByType()` won't find the extension (as it is added using a different version of the `DependencyLockCommitExtension` class), but the extension already exists under the name `commitDependencyLock`. Here's the error I get:

```text
Caused by: java.lang.IllegalArgumentException: Cannot add extension with name 'commitDependencyLock', as there is an extension already registered with that name.
	at org.gradle.api.internal.plugins.ExtensionsStorage.add(ExtensionsStorage.java:38)
	at org.gradle.api.internal.plugins.DefaultConvention.add(DefaultConvention.java:101)
	at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:107)
	at nebula.plugin.dependencylock.DependencyLockPlugin.apply(DependencyLockPlugin.groovy:41)
	at nebula.plugin.dependencylock.DependencyLockPlugin.apply(DependencyLockPlugin.groovy)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
	at com.prezi.gradle.boxfish.BoxfishModulePlugin.configureDependencyLocking(BoxfishModulePlugin.java:508)
	at com.prezi.gradle.boxfish.BoxfishModulePlugin.apply(BoxfishModulePlugin.java:80)
	at com.prezi.gradle.boxfish.BoxfishModulePlugin.apply(BoxfishModulePlugin.java:43)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:107)
	at com.prezi.gradle.boxfish.typescript.BoxfishTypeScriptPlugin.apply(BoxfishTypeScriptPlugin.java:24)
	at com.prezi.gradle.boxfish.typescript.BoxfishTypeScriptPlugin.apply(BoxfishTypeScriptPlugin.java:20)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
	... 44 more
```

I guess the problem is fundamentally with the approach to add an extension to the root project.

**Comment by bmuschko** [comment]
As a workaround you could probably just add the plugin to the buildscript classpath once in the root project. That'll make it available to all the subprojects.
