### ISSUE TITLE
Plugin should work with Gradle 2.4

### ISSUE THREAD

**Issue by elevenfive** [nebula-plugins/gradle-dependency-lock-plugin#56]
Using Gradle 2.4 I consistently get the following build exception:

```
Caused by: java.lang.CloneNotSupportedException: java.util.Collections$UnmodifiableSet
	at java.lang.Object.clone(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:230)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:112)
	at nebula.plugin.dependencylock.DependencyLockPlugin$_apply_closure1_closure26.doCall(DependencyLockPlugin.groovy:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at groovy.lang.Closure.call(Closure.java:439)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1379)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:1372)
	at org.codehaus.groovy.runtime.dgm$149.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:248)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:68)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at nebula.plugin.dependencylock.DependencyLockPlugin$_apply_closure1.doCall(DependencyLockPlugin.groovy:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:292)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1015)
	at groovy.lang.Closure.call(Closure.java:423)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:40)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.BroadcastDispatch.dispatch(BroadcastDispatch.java:87)
	... 61 more
```

**Comment by bmuschko** [comment]
It'll come up soon.

**Comment by rtyler** [comment]
@bmuschko from one plugin maintainer to another, I've had good experiences lately with @ysb33r's latest plugin [gradleTest](https://github.com/ysb33r/gradleTest) for testing against multiple Gradle versions.

I actually ran into this issue when I tried to incorporate the dependehcy-lock plugin as a default dependency in [a plugin I maintain](https://github.com/lookout/service-artifact-gradle-plugin) and my `gradleTest` task caught the failure on 2.4 :)

**Comment by oesolutions** [comment]
We are in the middle of migrating from Gradle 1.12 to 2.4 and ran into this issue. Either we need to wait on a fixed release (and possibly help make that happen), or we need to change course and target Gradle 2.3.

It seems like the 2.4 branch might already have a fix in place for this issue. Is there an estimate on when the 2.4 version could be released? If there are outstanding issues that need to be resolved first, please point me in the right direction and I'll see what resources we can provide as help.

**Comment by rspieldenner** [comment]
Working on updating publishing plugin to work in 2.4. Should be soon.

**Comment by rtyler** [comment]
@rspieldenner I've not dug into the source code enough for the plugin, but does it touch enough Gradle internals to make it difficult to track upstream Gradle releases more quickly?

2.5 was just released and the continuous build feature is something I'm quite keen on integrating into our internal developer workflows

**Comment by rspieldenner** [comment]
Dependency lock is easy to move our publishing plugin isn't. so we're stalled until I get that sorted which looks like early this week

**Comment by tjoneslo** [comment]
We also are in the stage of upgrading to Gradle 2.4, have hit this issue, and really need this plugin to work for us.

**Comment by jedi4ever** [comment]
there seems to be branch 2.4 - could you release a snapshot of this?
Or where can I get the snapshot from ?

**Comment by rspieldenner** [comment]
our plugin release process depends on other of our OSS plugins. I just got
the publishing plugin working so, will be moving through the rest of these
soon.

**Comment by chadjnsn** [comment]
Hey, I just wanted to check on this issue. Any luck on updating the publishing plugin/this plugin to work with gradle 2.4/5/6?

**Comment by dougborg** [comment]
Any updates on when the 2.4 branch will be released?

**Comment by pmorch** [comment]
Here is the error I'm getting - perhaps it'll help the next guy who googles - may he find this issue...

    * What went wrong:
    A problem occurred configuring root project 'jtest3'.
    > Failed to notify project evaluation listener.
       > java.util.Collections$UnmodifiableSet

I'm brand new to gradle, and seeing this plugin not working with the current version of gradle for 3½ months has me worried. So I have to ask: Are the any other gradle features / alternatives that let me track and lock down *transitive* / recursive dependencies I should check out first, or is this it?

**Comment by rspieldenner** [comment]
This is the only plugin I know of that does this. I'm slowly going through as time allows to move to new versions. My first priority is keeping internal builds working and we're still on 2.2.1. We accept pull requests to help keep things moving. This will go to 2.6 when I have the time.

**Comment by rspieldenner** [comment]
Releasing 3.0.0 in a few minutes. Supports 2.2.1-2.6 (that's what I've tested against).
