### ISSUE TITLE
Bad interaction with Dependency Substitution when updatinglock

### ISSUE THREAD

**Issue by datallah** [nebula-plugins/gradle-dependency-lock-plugin#63]
I'm using the 3.0.0 version of the plugin with gradle 2.6.

I have a project where I've specified a [dependencySubstitution](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:dependencySubstitution(org.gradle.api.Action)) block to prevent conflicting dependencies (as follows):

```
    configurations {
        all {
            resolutionStrategy {
                dependencySubstitution {
                    substitute module('org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec') with module('javax.jms:jms:1.1')
            }
        }
    }
```

The following is the stacktrace when running the updateGlobalLock task:
```
:updateGlobalLock FAILED
:updateGlobalLock took 16ms

FAILURE: Build failed with an exception.

* Where:
Build file '...\build.gradle' line: 450

* What went wrong:
Execution failed for task ':updateGlobalLock'.
> Could not find method module() for arguments [org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec] on configuration container.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':updateGlobalLock'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:62)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.MissingMethodException: Could not find method module() for arguments [org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec] on configuration container.
        at org.gradle.api.internal.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:68)
        at org.gradle.api.internal.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:56)
        at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:175)
        at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:62)
        at build_cgfo8xc7n4bfm926hqh9d1qv6$_run_closure4_closure31_closure54_closure55_closure56.doCall(...\build.gradle:450)
        at com.sun.proxy.$Proxy59.execute(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.resolutionstrategy.DefaultResolutionStrategy.dependencySubstitution(DefaultResolutionStrategy.java:162)
        at build_cgfo8xc7n4bfm926hqh9d1qv6$_run_closure4_closure31_closure54_closure55.doCall(...\build.gradle:449)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
        at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolutionStrategy(DefaultConfiguration.java:541)
        at build_cgfo8xc7n4bfm926hqh9d1qv6$_run_closure4_closure31_closure54.doCall(...\build.gradle:443)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
        at org.gradle.listener.ActionBroadcast.execute(ActionBroadcast.java:39)
        at org.gradle.api.internal.DefaultDomainObjectCollection.doAdd(DefaultDomainObjectCollection.java:165)
        at org.gradle.api.internal.DefaultDomainObjectCollection.add(DefaultDomainObjectCollection.java:159)
        at org.gradle.api.internal.DefaultNamedDomainObjectCollection.add(DefaultNamedDomainObjectCollection.java:81)
        at org.gradle.api.NamedDomainObjectCollection$add$0.call(Unknown Source)
        at nebula.plugin.dependencylock.DependencyLockPlugin$_configureGlobalLockTask_closure12_closure53_closure55.doCall(DependencyLockPlugin.groovy:259)
        at nebula.plugin.dependencylock.DependencyLockPlugin$_configureGlobalLockTask_closure12_closure53.doCall(DependencyLockPlugin.groovy:259)
        at org.gradle.api.internal.ConventionAwareHelper$1.getValue(ConventionAwareHelper.java:72)
        at org.gradle.api.internal.ConventionAwareHelper$MappedPropertyImpl.getValue(ConventionAwareHelper.java:136)
        at org.gradle.api.internal.ConventionAwareHelper.getConventionValue(ConventionAwareHelper.java:114)
        at nebula.plugin.dependencylock.tasks.UpdateLockTask_Decorated.getConfigurations(Unknown Source)
        at nebula.plugin.dependencylock.tasks.GenerateLockTask.lock(GenerateLockTask.groovy:36)
        at nebula.plugin.dependencylock.tasks.UpdateLockTask.super$5$lock(UpdateLockTask.groovy)
        at nebula.plugin.dependencylock.tasks.UpdateLockTask.lock(UpdateLockTask.groovy:57)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:226)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:219)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:208)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 14 more

BUILD FAILED
````

**Comment by datallah** [comment]
I ended up being able to work around the issue by changing the syntax slightly (explicitly calling **it.**substitute **it.**module). I'm not sure why it matters, but it works:
```
    configurations {
        all {
            resolutionStrategy {
                dependencySubstitution {
                    it.substitute it.module('org.jboss.spec.javax.jms:jboss-jms-api_1.1_spec') with module('javax.jms:jms:1.1')
                }
            }
        }
    }
```
